import pandas as pd
import hashlib
from datetime import datetime
from deltalake import DeltaTable, write_deltalake
import os

def create_version_hash(row, payload_cols):
    """Generates a SHA256 hash for the payload columns."""
    concat_str = "||".join([str(row[c]) for c in payload_cols])
    return hashlib.sha256(concat_str.encode('utf-8')).hexdigest()

def merge_scd2_micro_pandas(
    df_incoming: pd.DataFrame, 
    country_code: str, 
    table_path: str = "data/local_delta_catalog/lbs_micro", 
    date_scope: str = "2026-Q1", 
    ibs_agg_scope: str = "LBSR"
):
    target_path = f"{table_path}_{country_code.lower()}"
    payload_cols = ["OBS_VALUE"]
    
    # 1. Prepare Incoming Data
    df_source = df_incoming.copy()
    df_source['version_hash'] = df_source.apply(lambda r: create_version_hash(r, payload_cols), axis=1)
    
    current_time = pd.Timestamp.now('UTC')
    end_of_time = pd.Timestamp("9999-12-31 00:00:00")

    # 2. Initialize Table if it doesn't exist
    if not os.path.exists(target_path):
        df_init = df_source.copy()
        df_init['effective_start_date'] = current_time
        df_init['effective_end_date'] = end_of_time
        df_init['is_current'] = True
        
        write_deltalake(target_path, df_init, mode="overwrite")
        print(f"Initialized new Delta table at {target_path}")
        return

    # 3. Load Existing Delta Table
    dt = DeltaTable(target_path)
    df_target = dt.to_pandas()
    
    # Filter for active records
    active_target = df_target[df_target['is_current'] == True]

    # 4. Stage 1: Expire Changed Records
    # Find records where composite keys match but hash differs
    merged = pd.merge(
        active_target, 
        df_source, 
        on=["TIME_SERIES_CODE", "BANK_CODE", "DATE", "IBS_AGG"], 
        suffixes=('_tgt', '_src')
    )
    changed_records = merged[merged['version_hash_tgt'] != merged['version_hash_src']]
    
    if not changed_records.empty:
        # Use delta-rs native merge to update the old records
        dt.merge(
            source=changed_records[['TIME_SERIES_CODE', 'BANK_CODE', 'DATE', 'IBS_AGG']],
            predicate="s.TIME_SERIES_CODE = t.TIME_SERIES_CODE AND s.BANK_CODE = t.BANK_CODE AND t.is_current = true",
            source_alias="s",
            target_alias="t"
        ).when_matched_update(
            set={
                "is_current": "false",
                "effective_end_date": f"'{current_time}'"
            }
        ).execute()

    # 5. Stage 2: Insert New/Updated Records
    # Find records in source that are not in target, OR have a new hash
    merged_all = pd.merge(
        df_source, 
        active_target, 
        on=["TIME_SERIES_CODE", "BANK_CODE", "DATE", "IBS_AGG"], 
        how="left", 
        suffixes=('', '_tgt')
    )
    to_insert = merged_all[
        merged_all['version_hash_tgt'].isna() | 
        (merged_all['version_hash'] != merged_all['version_hash_tgt'])
    ].copy()
    
    if not to_insert.empty:
        # Clean up joined columns
        cols_to_keep = df_source.columns.tolist()
        to_insert = to_insert[cols_to_keep]
        to_insert['effective_start_date'] = current_time
        to_insert['effective_end_date'] = end_of_time
        to_insert['is_current'] = True
        
        write_deltalake(target_path, to_insert, mode="append")

    print(f"Processed SCD2 Merge for {country_code.upper()}.")

if __name__ == "__main__":
    try:
        # Load the CSV generated by your updated script
        df_ca_incoming = pd.read_csv("data/micro_transactions_ca.csv")
        
        print("Executing Pandas-Delta SCD2 Merge for Canada...")
        merge_scd2_micro_pandas(
            df_incoming=df_ca_incoming,
            country_code="ca"
        )
        
        # Verify the result
        dt_verify = DeltaTable("data/local_delta_catalog/lbs_micro_ca")
        print("\n--- Final Local Delta Table State ---")
        
        # Select columns to display, now including TIME_SERIES_CODE
        display_cols = ['TIME_SERIES_CODE', 'BANK_CODE', 'OBS_VALUE', 'is_current', 'version_hash']
        print(dt_verify.to_pandas()[display_cols])
        
    except FileNotFoundError:
        print("Error: CSV not found. Ensure generate_sovereign_submissions.py saved the CSV to data/")