"""Developer synthetic testing fixture: SCD2 without cluster compute.

This module exists so an external contributor can exercise and reason about the
historisation state machine on a laptop, with no Databricks workspace, no
credentials, and no JVM. It is a **development fixture**, never a deployment
target - `scd2_merge_engine.py` is the PySpark/Delta engine that runs in
production, and nothing here is imported by it.

What it faithfully reproduces:

* the quarantine state machine - a rejected revision is appended as an
  audit-only row and never expires the prior published record
* `version_hash` change detection over the payload columns
* replay idempotency, so a re-run does not stack duplicate audit rows

Where it deliberately differs, and why it does not matter for the fixture's
purpose:

* **Column naming.** New local history uses `VALID_FROM`, `VALID_TO` and
    `IS_CURRENT`, matching the macro contract. Legacy local tables require an
    explicit migration or a separately generated synthetic catalog.
* **Per-country tables.** Writes to `data/local_delta_catalog/lbs_micro_<cc>`
  rather than a single governed table, so sovereign isolation is expressed by
  file layout instead of a row filter. Unity Catalog is the enforcement point
  in every deployed configuration; nothing here enforces entitlement.

For the persona matrix equivalent of this fixture, see `LocalDeltaBackend` in
`uc_query.py`. Both are exercised offline by `tests/`.

Related skill: `.github/skills/scd2_engine.md`.
"""

import pandas as pd
import hashlib
from datetime import datetime
from deltalake import DeltaTable

def create_version_hash(row, payload_cols):
    """Generates a SHA256 hash for the payload columns."""
    concat_str = "||".join([str(row[c]) for c in payload_cols])
    return hashlib.sha256(concat_str.encode('utf-8')).hexdigest()

def merge_scd2_micro_pandas(
    df_incoming: pd.DataFrame, 
    country_code: str, 
    table_path: str = "data/local_delta_catalog/lbs_micro", 
    date_scope: str = "2026-Q1", 
    agg_scope: str = "LBSR"
):
    """Compatibility fixture using the atomic history contract and uppercase history fields.

    Supply SUBMISSION_ID, SOURCE_SHA256 and SUBMITTED_AT in DataFrame.attrs for
    arrival-aware replay. Without them, content identity is a legacy fixture
    convenience and cannot distinguish identical new filings.
    """
    from datetime import timezone
    from submission_history import SubmissionContext, merge_local_submission, stable_hash

    source = df_incoming.copy()
    if not source["TIME_SERIES_CODE"].str.split(".").str[8].eq(country_code.upper()).all():
        raise ValueError("Local country scope disagrees with the submission.")
    if "BATCH_STATUS" not in source:
        source["BATCH_STATUS"] = "PUBLISHED"
    if "QUALITY_STATUS" not in source:
        source["QUALITY_STATUS"] = source["BATCH_STATUS"].map({"PUBLISHED": "PASS", "QUARANTINE": "FAIL"})
    for name, default in (("OBS_STATUS", "A"), ("OBS_CONF", "N")):
        if name not in source:
            source[name] = default
    content_hash = stable_hash(source.sort_values(["TIME_SERIES_CODE", "BANK_CODE", "DATE", "AGG_CODE"]).astype(str).to_numpy().ravel().tolist())
    now = datetime.now(timezone.utc)
    context = SubmissionContext(
        source.attrs.get("SUBMISSION_ID", f"local-content:{content_hash}"),
        source.attrs.get("SOURCE_SHA256", content_hash),
        pd.Timestamp(source.attrs.get("SUBMITTED_AT", now)).to_pydatetime(), now,
    )
    return merge_local_submission(f"{table_path}_{country_code.lower()}", source, context)

if __name__ == "__main__":
    try:
        # Load the CSV generated by your updated script
        df_ca_incoming = pd.read_csv("data/micro_transactions_ca.csv")
        
        print("Executing Pandas-Delta SCD2 Merge for Canada...")
        merge_scd2_micro_pandas(
            df_incoming=df_ca_incoming,
            country_code="ca"
        )
        
        # Verify the result
        dt_verify = DeltaTable("data/local_delta_catalog/lbs_micro_ca")
        print("\n--- Final Local Delta Table State ---")
        
        # Select columns to display, now including TIME_SERIES_CODE
        display_cols = ['TIME_SERIES_CODE', 'BANK_CODE', 'OBS_VALUE', 'BATCH_STATUS', 'is_current', 'version_hash']
        df_final = dt_verify.to_pandas()
        print(df_final[[c for c in display_cols if c in df_final.columns]])
        
    except FileNotFoundError:
        print("Error: CSV not found. Ensure generate_sovereign_submissions.py saved the CSV to data/")